{"name":"Dataverse Metadata","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-05-13T17:39:47.561156+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"DataLakeEnvironmentURL":{"queryId":"c35ea245-2b04-4a9e-ab35-8fb8f64a7983","queryName":"DataLakeEnvironmentURL","queryGroupId":"96b8c03c-01c6-4dc7-9807-f0baa4101ac9"},"Option Sets":{"queryId":"36a6d8bb-8df8-4cd7-a509-f4cefaf86a40","queryName":"Option Sets","queryGroupId":"e79ac334-a34b-463f-8073-324de0a68db6","loadEnabled":true},"Table Relationships":{"queryId":"82196ae3-1409-4840-bee6-5f38554ced75","queryName":"Table Relationships","queryGroupId":"e79ac334-a34b-463f-8073-324de0a68db6","loadEnabled":true},"Field Metadata":{"queryId":"b6fac869-59cb-41fc-97fc-5f7994d5b602","queryName":"Field Metadata","queryGroupId":"e79ac334-a34b-463f-8073-324de0a68db6","loadEnabled":true}},"document":"section Section1;\r\n[Description = \"https://{datalakeid}.dfs.core.windows.net/{dataverse container}#(lf)#(lf){datalakeid} = Name of your Storage account.#(lf){dataverse container} = The container name automatically created when the Dataverse sync is setup.\"]\r\nshared DataLakeEnvironmentURL = \"https://datalakeid.dfs.core.windows.net/dataverse-container\" meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type any];\r\nshared #\"Option Sets\" = let\n    // The Data Lake (Data Storage) Environment/Blob connected to Dataverse.\n    Source = AzureStorage.DataLake(DataLakeEnvironmentURL),\n\n    // Filter on the Metadata files only.\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\n\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\n\n    // The table name is required to resolve Global Option Sets for downstream processes. Table name isn't available in the json file for Global Option Set type.\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\n\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each Record.ToTable(Json.Document([Content]))),\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\n    #\"Remove columns related to source files\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\n\n    // Remove the metadata types not related to Option Sets.\n    #\"Filtered Option Sets\" = Table.SelectRows(#\"Remove columns related to source files\", each ([Metadata Type] <> \"AttributeMetadata\" and [Metadata Type] <> \"TargetMetadata\")),\n\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered Option Sets\", \"Value\"),\n    #\"Expanded Records to Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"State\", \"Status\", \"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\", \"LocalizedLabel\"}, {\"State\", \"Status\", \"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\", \"Option Field Label\"}),\n\n    // Put the integer fields in a single column.\n    #\"Combined Option Id\" = Table.TransformColumnTypes(Table.AddColumn(#\"Expanded Records to Fields\", \"Option Id\", each if [Metadata Type] = \"StateMetadata\" then [State] else if [Metadata Type] = \"StatusMetadata\" then [Status] else [Option]), {{\"Option Id\", Int64.Type}}),\n\n    // Put the field names in a single column.\n    #\"Combined Field Name\" = Table.TransformColumnTypes(Table.AddColumn(#\"Combined Option Id\", \"Field Name\", each if [Metadata Type] = \"StateMetadata\" then \"statecode\" else if [Metadata Type] = \"StatusMetadata\" then \"statuscode\" else [OptionSetName]), {{\"Field Name\", type text}}),\n\n    #\"Remove duplicate columns\" = Table.RemoveColumns(#\"Combined Field Name\", {\"Option\", \"OptionSetName\"}),\n    #\"Assign every column a type\" = Table.TransformColumnTypes(#\"Remove duplicate columns\", {{\"Option Field Label\", type text}, {\"Metadata Type\", type text}, {\"State\", Int64.Type}, {\"Status\", Int64.Type}, {\"IsUserLocalizedLabel\", type logical}, {\"LocalizedLabelLanguageCode\", type text}})\nin\n    #\"Assign every column a type\";\r\nshared #\"Table Relationships\" = let\n    Source = AzureStorage.DataLake(DataLakeEnvironmentURL),\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each Record.ToTable(Json.Document([Content]))),\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\n    #\"Removed columns\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\n    #\"Filtered TargetMetadata\" = Table.SelectRows(#\"Removed columns\", each [Metadata Type] = \"TargetMetadata\"),\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered TargetMetadata\", \"Value\"),\n    #\"Expanded Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"AttributeName\", \"ReferencedEntity\", \"ReferencedAttribute\"}, {\"Field Name\", \"Related Table Name\", \"Related Field Name\"}),\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Fields\", {{\"Metadata Type\", type text}, {\"Field Name\", type text}, {\"Related Table Name\", type text}, {\"Related Field Name\", type text}})\nin\n    #\"Changed column type\";\r\nshared #\"Field Metadata\" = let\n    Source = AzureStorage.DataLake(DataLakeEnvironmentURL),\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each Record.ToTable(Json.Document([Content]))),\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\n    #\"Removed columns\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\n    #\"Filtered AttributeMetadata\" = Table.SelectRows(#\"Removed columns\", each [Metadata Type] = \"AttributeMetadata\"),\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered AttributeMetadata\", \"Value\"),\n    #\"Expanded Records to Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"AttributeName\", \"AttributeType\", \"AttributeTypeCode\", \"Version\", \"Timestamp\", \"MetadataId\", \"Precision\", \"MaxLength\"}, {\"Field Name\", \"Field Type\", \"Field Type Code\", \"Version\", \"Timestamp\", \"MetadataId\", \"Precision\", \"Max Length\"}),\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Records to Fields\", {{\"Metadata Type\", type text}, {\"Field Name\", type text}, {\"Field Type\", type text}, {\"MetadataId\", type text}, {\"Field Type Code\", Int64.Type}, {\"Version\", Int64.Type}, {\"Precision\", Int64.Type}, {\"Max Length\", Int64.Type}, {\"Timestamp\", type datetime}})\nin\n    #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"96b8c03c-01c6-4dc7-9807-f0baa4101ac9\",\"name\":\"Parameters\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"e79ac334-a34b-463f-8073-324de0a68db6\",\"name\":\"Metadata Queries\",\"description\":\"\",\"parentId\":null,\"order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"Option Sets","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Option%20Sets.csv"},"attributes":[{"name":"Table Name","dataType":"string"},{"name":"Date modified","dataType":"dateTime"},{"name":"Metadata Type","dataType":"string"},{"name":"State","dataType":"int64"},{"name":"Status","dataType":"int64"},{"name":"IsUserLocalizedLabel","dataType":"boolean"},{"name":"LocalizedLabelLanguageCode","dataType":"string"},{"name":"Option Field Label","dataType":"string"},{"name":"Option Id","dataType":"int64"},{"name":"Field Name","dataType":"string"}]},{"$type":"LocalEntity","name":"Table Relationships","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Table%20Relationships.csv"},"attributes":[{"name":"Table Name","dataType":"string"},{"name":"Date modified","dataType":"dateTime"},{"name":"Metadata Type","dataType":"string"},{"name":"Field Name","dataType":"string"},{"name":"Related Table Name","dataType":"string"},{"name":"Related Field Name","dataType":"string"}]},{"$type":"LocalEntity","name":"Field Metadata","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Field%20Metadata.csv"},"attributes":[{"name":"Table Name","dataType":"string"},{"name":"Date modified","dataType":"dateTime"},{"name":"Metadata Type","dataType":"string"},{"name":"Field Name","dataType":"string"},{"name":"Field Type","dataType":"string"},{"name":"Field Type Code","dataType":"int64"},{"name":"Version","dataType":"int64"},{"name":"Timestamp","dataType":"dateTime"},{"name":"MetadataId","dataType":"string"},{"name":"Precision","dataType":"int64"},{"name":"Max Length","dataType":"int64"}]}]}