{"name":"Dataverse Metadata","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-05-12T23:34:21.242358+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"DataLakeURL":{"queryId":"c35ea245-2b04-4a9e-ab35-8fb8f64a7983","queryName":"DataLakeURL","queryGroupId":"96b8c03c-01c6-4dc7-9807-f0baa4101ac9"},"TransformJSONtoTable":{"queryId":"6233a8f9-e758-45f9-addd-4a941be044fc","queryName":"TransformJSONtoTable","queryGroupId":"cfa2505f-73b7-462f-a380-3fa8c14a46d8"},"Option Sets":{"queryId":"36a6d8bb-8df8-4cd7-a509-f4cefaf86a40","queryName":"Option Sets","queryGroupId":"e79ac334-a34b-463f-8073-324de0a68db6","loadEnabled":true},"Table Relationships":{"queryId":"82196ae3-1409-4840-bee6-5f38554ced75","queryName":"Table Relationships","queryGroupId":"e79ac334-a34b-463f-8073-324de0a68db6","loadEnabled":true},"Field Metadata":{"queryId":"b6fac869-59cb-41fc-97fc-5f7994d5b602","queryName":"Field Metadata","queryGroupId":"e79ac334-a34b-463f-8073-324de0a68db6","loadEnabled":true},"RangeStart":{"queryId":"9ec5edee-1a0f-451b-89b9-b573a84b2712","queryName":"RangeStart"},"RangeEnd":{"queryId":"925fb404-52a1-426a-97f3-681cd027f7e8","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\n    [Description = \"https://{datalakeid}.dfs.core.windows.net/{dataverse folder}/Microsoft.Athena.TrickleFeedService#(lf)#(lf){datalakeid} = Name of your Storage account.#(lf){dataverse folder} = The folder name automatically created when the Dataverse sync is setup.\"]\r\nshared DataLakeURL = \"https://datalakeid.dfs.core.windows.net/dataversefolder/Microsoft.Athena.TrickleFeedService\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any];\r\n\r\nshared TransformJSONtoTable = (Parameter as binary) => let\r\n    Source = Json.Document(Parameter),\r\n    #\"Converted to table\" = Record.ToTable(Source)\r\nin\r\n    #\"Converted to table\";\r\n\r\nshared #\"Option Sets\" = let\r\n    Source = AzureStorage.DataLake(DataLakeURL),\r\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\r\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\r\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each TransformJSONtoTable([Content])),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\r\n    #\"Removed columns\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\r\n    #\"Filtered Option Sets\" = Table.SelectRows(#\"Removed columns\", each ([Metadata Type] <> \"AttributeMetadata\" and [Metadata Type] <> \"TargetMetadata\")),\r\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered Option Sets\", \"Value\"),\r\n    #\"Expanded Records to Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"State\", \"Status\", \"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\", \"LocalizedLabel\"}, {\"State\", \"Status\", \"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\", \"Option Field Label\"}),\r\n    #\"Added Option Id\" = Table.TransformColumnTypes(Table.AddColumn(#\"Expanded Records to Fields\", \"Option Id\", each if [Metadata Type] = \"StateMetadata\" then [State] else if [Metadata Type] = \"StatusMetadata\" then [Status] else [Option]), {{\"Option Id\", Int64.Type}}),\r\n    #\"Added Field Name\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added Option Id\", \"Field Name\", each if [Metadata Type] = \"StateMetadata\" then \"statecode\" else if [Metadata Type] = \"StatusMetadata\" then \"statuscode\" else [OptionSetName]), {{\"Field Name\", type text}}),\r\n    #\"Removed columns 1\" = Table.RemoveColumns(#\"Added Field Name\", {\"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed columns 1\", {{\"Option Field Label\", type text}, {\"Metadata Type\", type text}, {\"State\", Int64.Type}, {\"Status\", Int64.Type}}),\r\n    #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type\", {\"Table Name\", \"Field Name\", \"Option Id\", \"Option Field Label\", \"State\", \"Status\", \"Date modified\", \"Metadata Type\"})\r\nin\r\n    #\"Reordered columns\";\r\n\r\nshared #\"Table Relationships\" = let\r\n    Source = AzureStorage.DataLake(DataLakeURL),\r\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\r\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\r\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each TransformJSONtoTable([Content])),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\r\n    #\"Removed columns\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\r\n    #\"Filtered TargetMetadata\" = Table.SelectRows(#\"Removed columns\", each [Metadata Type] = \"TargetMetadata\"),\r\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered TargetMetadata\", \"Value\"),\r\n    #\"Expanded Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"AttributeName\", \"ReferencedEntity\", \"ReferencedAttribute\"}, {\"Field Name\", \"Related Table Name\", \"Related Field Name\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Fields\", {{\"Metadata Type\", type text}, {\"Field Name\", type text}, {\"Related Table Name\", type text}, {\"Related Field Name\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Field Metadata\" = let\r\n    Source = AzureStorage.DataLake(DataLakeURL),\r\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\r\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\r\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each TransformJSONtoTable([Content])),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\r\n    #\"Removed columns\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\r\n    #\"Filtered AttributeMetadata\" = Table.SelectRows(#\"Removed columns\", each [Metadata Type] = \"AttributeMetadata\"),\r\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered AttributeMetadata\", \"Value\"),\r\n    #\"Expanded Records to Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"AttributeName\", \"AttributeType\", \"AttributeTypeCode\", \"Version\", \"Timestamp\", \"MetadataId\", \"Precision\", \"MaxLength\"}, {\"Field Name\", \"Field Type\", \"Field Type Code\", \"Version\", \"Timestamp\", \"MetadataId\", \"Precision\", \"Max Length\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Records to Fields\", {{\"Metadata Type\", type text}, {\"Field Name\", type text}, {\"Field Type\", type text}, {\"MetadataId\", type text}, {\"Field Type Code\", Int64.Type}, {\"Version\", Int64.Type}, {\"Precision\", Int64.Type}, {\"Max Length\", Int64.Type}, {\"Timestamp\", type datetime}}),\r\n    #\"Field Metadata-44617465206D6F646966696564-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type\", each DateTime.From([#\"Date modified\"]) >= RangeStart and DateTime.From([#\"Date modified\"]) < RangeEnd)\r\nin\r\n    #\"Field Metadata-44617465206D6F646966696564-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"96b8c03c-01c6-4dc7-9807-f0baa4101ac9\",\"name\":\"Parameters\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"e79ac334-a34b-463f-8073-324de0a68db6\",\"name\":\"Metadata Queries\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"cfa2505f-73b7-462f-a380-3fa8c14a46d8\",\"name\":\"Functions\",\"description\":\"\",\"parentId\":null,\"order\":2}]"}],"entities":[{"$type":"LocalEntity","name":"Option Sets","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Option%20Sets.csv"},"attributes":[{"name":"Table Name","dataType":"string"},{"name":"Field Name","dataType":"string"},{"name":"Option Id","dataType":"int64"},{"name":"Option Field Label","dataType":"string"},{"name":"State","dataType":"int64"},{"name":"Status","dataType":"int64"},{"name":"Date modified","dataType":"dateTime"},{"name":"Metadata Type","dataType":"string"}]},{"$type":"LocalEntity","name":"Table Relationships","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Table%20Relationships.csv"},"attributes":[{"name":"Table Name","dataType":"string"},{"name":"Date modified","dataType":"dateTime"},{"name":"Metadata Type","dataType":"string"},{"name":"Field Name","dataType":"string"},{"name":"Related Table Name","dataType":"string"},{"name":"Related Field Name","dataType":"string"}]},{"$type":"LocalEntity","name":"Field Metadata","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"Field%20Metadata/part.csv","rollingWindowGranularity":"day","rollingWindowPeriods":1,"incrementalGranularity":"day","incrementalPeriods":1},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"Date modified"}],"attributes":[{"name":"Table Name","dataType":"string"},{"name":"Date modified","dataType":"dateTime"},{"name":"Metadata Type","dataType":"string"},{"name":"Field Name","dataType":"string"},{"name":"Field Type","dataType":"string"},{"name":"Field Type Code","dataType":"int64"},{"name":"Version","dataType":"int64"},{"name":"Timestamp","dataType":"dateTime"},{"name":"MetadataId","dataType":"string"},{"name":"Precision","dataType":"int64"},{"name":"Max Length","dataType":"int64"}]}]}