{"name":"Load a Dataverse Table","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-05-13T17:49:53.4413512+00:00","pbi:mashup":{"fastCombine":true,"allowNativeQueries":false,"queriesMetadata":{"OptionSetTable":{"queryId":"f9d4792a-5782-4406-859e-0ab20322cc67","queryName":"OptionSetTable","queryGroupId":"723313bf-b560-4084-85ab-7152850b1b1b"},"Instructions":{"queryId":"1133a374-3c60-4ac8-8112-4543eedd2cef","queryName":"Instructions","queryGroupId":"3ae233e4-ad08-4252-88f6-c2f011198603","loadEnabled":true},"DataLakeEnvironmentURL":{"queryId":"1cbcf236-a5f2-4b32-9b54-321fbb0b67e1","queryName":"DataLakeEnvironmentURL","queryGroupId":"3ae233e4-ad08-4252-88f6-c2f011198603"},"fnEnhancedDataverseTableFromDataLake":{"queryId":"770a6839-7359-439d-972b-329812abcd13","queryName":"fnEnhancedDataverseTableFromDataLake","queryGroupId":"3ae233e4-ad08-4252-88f6-c2f011198603"},"Expanded Table - Account":{"queryId":"08459626-ee2b-4fb2-b572-eb8082ad86af","queryName":"Expanded Table - Account","queryGroupId":"85e2bd2d-ab5e-413c-abc8-f061b93b535e"}},"document":"section Section1;\r\nshared OptionSetTable = let\n    // The Data Lake (Data Storage) Environment/Blob connected to Dataverse.\n    Source = AzureStorage.DataLake(DataLakeEnvironmentURL),\n\n    // Filter on the Metadata files only.\n    #\"Filtered EntityMetadata.json\" = Table.SelectRows(Source, each Text.Contains([Name], \"EntityMetadata.json\")),\n\n    #\"Renamed columns\" = Table.RenameColumns(#\"Filtered EntityMetadata.json\", {{\"Name\", \"Table Name\"}}),\n\n    // The table name is required to resolve Global Option Sets for downstream processes. Table name isn't available in the json file for Global Option Set type.\n    #\"Get Table Name from File Name\" = Table.ReplaceValue(#\"Renamed columns\", \"-EntityMetadata.json\", \"\", Replacer.ReplaceText, {\"Table Name\"}),\n\n    #\"Parse JSON to Table\" = Table.AddColumn(#\"Get Table Name from File Name\", \"Transform file\", each Record.ToTable(Json.Document([Content]))),\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Parse JSON to Table\", \"Transform file\", {\"Name\", \"Value\"}, {\"Metadata Type\", \"Value\"} ),\n    #\"Remove columns related to source files\" = Table.RemoveColumns(#\"Expanded table column\", {\"Content\", \"Extension\", \"Date accessed\", \"Date created\", \"Attributes\", \"Folder Path\"}),\n\n    // Remove the metadata types not related to Option Sets.\n    #\"Filtered Option Sets\" = Table.SelectRows(#\"Remove columns related to source files\", each ([Metadata Type] <> \"AttributeMetadata\" and [Metadata Type] <> \"TargetMetadata\")),\n\n    #\"Expanded List to Records\" = Table.ExpandListColumn(#\"Filtered Option Sets\", \"Value\"),\n    #\"Expanded Records to Fields\" = Table.ExpandRecordColumn(#\"Expanded List to Records\", \"Value\", {\"State\", \"Status\", \"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\", \"LocalizedLabel\"}, {\"State\", \"Status\", \"Option\", \"OptionSetName\", \"IsUserLocalizedLabel\", \"LocalizedLabelLanguageCode\", \"Option Field Label\"}),\n\n    // Put the integer fields in a single column.\n    #\"Combined Option Id\" = Table.TransformColumnTypes(Table.AddColumn(#\"Expanded Records to Fields\", \"Option Id\", each if [Metadata Type] = \"StateMetadata\" then [State] else if [Metadata Type] = \"StatusMetadata\" then [Status] else [Option]), {{\"Option Id\", Int64.Type}}),\n\n    // Put the field names in a single column.\n    #\"Combined Field Name\" = Table.TransformColumnTypes(Table.AddColumn(#\"Combined Option Id\", \"Field Name\", each if [Metadata Type] = \"StateMetadata\" then \"statecode\" else if [Metadata Type] = \"StatusMetadata\" then \"statuscode\" else [OptionSetName]), {{\"Field Name\", type text}}),\n\n    #\"Remove duplicate columns\" = Table.RemoveColumns(#\"Combined Field Name\", {\"Option\", \"OptionSetName\"}),\n    #\"Assign every column a type\" = Table.TransformColumnTypes(#\"Remove duplicate columns\", {{\"Option Field Label\", type text}, {\"Metadata Type\", type text}, {\"State\", Int64.Type}, {\"Status\", Int64.Type}, {\"IsUserLocalizedLabel\", type logical}, {\"LocalizedLabelLanguageCode\", type text}})\nin\n    #\"Assign every column a type\";\r\nshared Instructions = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dcoxDoJAEAXQq/xMrd7BKN0WhGgFW3zZSSDgrFmGRG+PIbbW77WtVOZa8MlrwZVOBE6KexMwGnxQ1Cx86vecJB7+9EvRpOYj5+WX+JgVITMhGzqp3i9a0oTbDkec+z6v5p1IjBs=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Instructions = _t])\r\nin\r\n  Source;\r\n[Description = \"https://{Data Storage Account Name}.dfs.core.windows.net/{Dataverse Container Name}\"]\r\nshared DataLakeEnvironmentURL = \"https://example.com\" meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type text];\r\nshared fnEnhancedDataverseTableFromDataLake = let \n  fnEnhancedDataverseTableFromDataLake = (DataverseTableName) as table => \n    let\n      Source = Cdm.Contents(AzureStorage.DataLake(DataLakeEnvironmentURL, [HierarchicalNavigation = true])),\n      Navigation = Source{[Id = \"model.json\"]}[Data],\n      #\"Navigation 1\" = Navigation{[Name = DataverseTableName]}[Data],\n\n      // Define the Dataverse table and the Option Set table\n      DataverseTable = Table.Buffer(#\"Navigation 1\"),\n      OptionSetTableLocal = Table.Buffer(Table.SelectRows(OptionSetTable, each ([Table Name] = DataverseTableName))),\n\n      // Boolean fields to be 0 or 1 instead of \"True\" or \"False\"\n      DataverseTableSchema = Table.Schema(DataverseTable),\n      BooleanColumns = Table.Column(Table.SelectRows(DataverseTableSchema, each ([TypeName] = \"Logical.Type\")),\"Name\"),\n      DataverseTableInts = Table.TransformColumnTypes(DataverseTable, \n        List.Transform(BooleanColumns, each { _ , Int64.Type})),\n      \n      // List of Option Columns to resolve name columns\n      OptionColumns = List.Intersect({Table.ColumnNames(DataverseTable), List.Distinct(Table.Column(OptionSetTableLocal,\"Field Name\"))}),\n      CountColumns = List.Count(OptionColumns),\n\n      // Recursive function that joins each option column with the Option Set table and returns many {optionfield}name columns. Function called in subsequent step.\n      fnTableJoinRecursion = (CombinedTable, i, CountColumnsLocal) as table =>\n        let\n          UpdatedTable = Table.NestedJoin(\n              CombinedTable, \n              {OptionColumns{i}}, \n              Table.SelectRows(OptionSetTableLocal , each ([Field Name] = OptionColumns{i})), \n              {\"Option Id\"}, \n              OptionColumns{i} & \"Table\", \n              JoinKind.LeftOuter),\n          UpdatedTableExpanded = Table.ExpandTableColumn(UpdatedTable, OptionColumns{i} & \"Table\", {\"Option Field Label\"}, {OptionColumns{i} & \"name\"}),\n          CheckComplete = \n            if i < (CountColumnsLocal - 1) then @fnTableJoinRecursion(UpdatedTableExpanded, i + 1, CountColumnsLocal)\n            else UpdatedTableExpanded\n        in\n          CheckComplete,\n\n      // If there are option columns, run the recursive function to add the \"name\" columns, otherwise return the table\n      DataverseTableWithNameFields = if CountColumns > 0 then fnTableJoinRecursion(DataverseTableInts, 0 , CountColumns) else DataverseTableInts\n\n      // It's possible but not necessary to sort the columns alphabetically.\n      // DataverseTableSorted = Table.ReorderColumns( DataverseTableWithNameFields, List.Sort( Table.ColumnNames( DataverseTableWithNameFields ), Order.Ascending ))\n    in\n      DataverseTableWithNameFields\nin\n  fnEnhancedDataverseTableFromDataLake;\r\nshared #\"Expanded Table - Account\" = let\r\n  Source = fnEnhancedDataverseTableFromDataLake(\"account\")\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"723313bf-b560-4084-85ab-7152850b1b1b\",\"name\":\"OptionSetTable Function\",\"description\":\"\",\"parentId\":null,\"order\":2},{\"id\":\"3ae233e4-ad08-4252-88f6-c2f011198603\",\"name\":\"Parameters and Functions\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"85e2bd2d-ab5e-413c-abc8-f061b93b535e\",\"name\":\"Examples\",\"description\":\"\",\"parentId\":null,\"order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"Instructions","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Instructions.csv"},"attributes":[{"name":"Instructions","dataType":"string"}]}]}